<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document [
<!ELEMENT document (head, body)>
<!ELEMENT head (title, meta*, script*, noscript*, link*)>
<!ELEMENT body (main)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT meta EMPTY>
<!ELEMENT script (#PCDATA)>
<!ELEMENT noscript (#PCDATA)>
<!ELEMENT link EMPTY>
<!ELEMENT main (noscript?, p+)>
<!ELEMENT p (#PCDATA)>
<!ATTLIST meta http-equiv CDATA #IMPLIED charset CDATA #IMPLIED>
<!ATTLIST script type CDATA #REQUIRED>
<!ATTLIST link rel CDATA #IMPLIED href CDATA #REQUIRED type CDATA #IMPLIED title CDATA #IMPLIED>
<!ATTLIST main role CDATA #IMPLIED>
]>
<document>
  <head>
    <title>Generated Documentation (Untitled)</title>
    <meta http-equiv="Content-Type" charset="utf-8"/>
    <script type="text/javascript">window.location.replace('Tema2/Tarea/Documentacion/index.html')</script>
    <noscript>
      <meta http-equiv="Refresh" content="0;Tema2/Tarea/Documentacion/index.html"/>
    </noscript>
    <link rel="canonical" href="Tema2/Tarea/Documentacion/index.html"/>
    <link rel="stylesheet" type="text/css" href="stylesheet.css" title="Style"/>
  </head>
  <body>
    <main role="main">
      <noscript>
        <p>JavaScript is disabled on your browser.</p>
      </noscript>
      <p><a href="Tema2/Tarea/package-summary.html">Tema2/Tarea/Documentacion/index.html</a></p>
    </main>
  </body>
</document>